name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main
    - dev
    - development
    - staging

env:
  CI: true
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  HUSKY_SKIP_INSTALL: true

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: echo if should run
      if: github.event.pull_request.draft == true
      run: |
        echo "Feels okay man."
        echo '::warning:: PR is in draft'
        echo "::stop-commands::$stopMarker"

    - name: how about this?
      run: |
        echo "Feels bad man."
        echo '::warning:: PR is in draft'
        echo "::stop-commands::$stopMarker"
